name: Execute Split Script

on:
  workflow_dispatch: # لتشغيل السكربت يدوياً بضغطة زر

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Execute split.py
        run: python split.py

      - name: Save and Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add index.html style.css script.js
          git commit -m "Refactor: Split files using split.py" || echo "No changes to commit"
          git push
